//go:build ignore

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type wikiPage struct {
	File    string
	Title   string
	Content string
}

func main() {
	root := "."
	docsDir := filepath.Join(root, "docs")
	metaDir := filepath.Join(docsDir, "meta")
	refDir := filepath.Join(docsDir, "reference")
	guidesDir := filepath.Join(docsDir, "guides")
	wikiDir := filepath.Join(root, "wiki")

	os.MkdirAll(wikiDir, 0755)

	pages := []wikiPage{
		buildHomePage(root, docsDir, metaDir, refDir, guidesDir),
		buildToolsPage(refDir),
		buildArchitecturePage(docsDir),
		buildPlanPage(metaDir),
		buildBacklogPage(metaDir),
		buildChangelogPage(metaDir),
		buildKnownIssuesPage(metaDir),
		buildSecurityPage(root, docsDir),
		buildBuildUsagePage(root),
		buildConfigPage(refDir),
		buildReferenceDocsPage(refDir),
		buildGuidesPage(guidesDir),
		buildCICDPage(docsDir),
	}

	for _, p := range pages {
		path := filepath.Join(wikiDir, p.File)
		header := fmt.Sprintf("<!-- Auto-generated from project docs. Run `go run ./scripts/gen-wiki.go` to regenerate. -->\n\n# %s\n\n", p.Title)
		if p.File != "Home.md" {
			header += "[Home](Home.md) ← "
		}
		full := header + p.Content + "\n\n<!-- Generated by scripts/gen-wiki.go -->\n"
		if err := os.WriteFile(path, []byte(full), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "error writing %s: %v\n", path, err)
			os.Exit(1)
		}
		fmt.Printf("wrote %s\n", path)
	}
	fmt.Printf("wiki: %d pages in %s\n", len(pages), wikiDir)
}

func buildHomePage(root, docsDir, metaDir, refDir, guidesDir string) wikiPage {
	var b strings.Builder

	readSection(root, "README.md", &b, 1, 19)
	b.WriteString("\n---\n\n## Features\n\n")
	readSection(root, "README.md", &b, 21, 47)
	b.WriteString("\n## Tools\n\n")
	readSection(root, "README.md", &b, 49, 53)
	b.WriteString("\n## Quick Links\n\n")
	b.WriteString("- [Tools Reference](Tools-Reference) — all 132 MCP tools by category\n")
	b.WriteString("- [Architecture](Architecture) — agent stack and code map\n")
	b.WriteString("- [Project Plan](Project-Plan) — progress and prioritized work\n")
	b.WriteString("- [Backlog](Backlog) — 385-item roadmap\n")
	b.WriteString("- [Changelog](Changelog) — release history\n")
	b.WriteString("- [Known Issues](Known-Issues) — bugs and workarounds\n")
	b.WriteString("- [Security](Security) — security model and data collection\n")
	b.WriteString("- [Build & Usage](Build-Usage) — requirements and build commands\n")
	b.WriteString("- [Configuration](Configuration) — config file reference\n")
	b.WriteString("- [Reference Docs](Reference-Docs) — full reference documentation\n")
	b.WriteString("- [Guides](Guides) — usage guides\n")
	b.WriteString("- [CI/CD Pipeline](CICD) — CI/CD workflow documentation\n")
	b.WriteString("\n## Documentation\n\n")
	readSection(root, "README.md", &b, 82, 99)
	b.WriteString("\n")

	return wikiPage{File: "Home.md", Title: "go-mcp-computer-use Wiki", Content: b.String()}
}

func buildToolsPage(refDir string) wikiPage {
	var b strings.Builder
	data, err := os.ReadFile(filepath.Join(refDir, "tools.md"))
	if err != nil {
		b.WriteString("_Run `go run ./scripts/gen-tools-doc.go` to generate._\n")
	} else {
		b.WriteString(string(data))
	}
	return wikiPage{File: "Tools-Reference.md", Title: "Tools Reference", Content: b.String()}
}

func buildArchitecturePage(docsDir string) wikiPage {
	var b strings.Builder
	data, err := os.ReadFile(filepath.Join(docsDir, "architecture.md"))
	if err != nil {
		b.WriteString("_Architecture document not found._\n")
	} else {
		writeFullDoc(&b, string(data))
	}
	return wikiPage{File: "Architecture.md", Title: "Architecture", Content: b.String()}
}

func buildPlanPage(metaDir string) wikiPage {
	var b strings.Builder
	data, err := os.ReadFile(filepath.Join(metaDir, "plan.md"))
	if err != nil {
		b.WriteString("_Plan document not found._\n")
	} else {
		writeFullDoc(&b, string(data))
	}
	return wikiPage{File: "Project-Plan.md", Title: "Project Plan", Content: b.String()}
}

func buildBacklogPage(metaDir string) wikiPage {
	var b strings.Builder
	data, err := os.ReadFile(filepath.Join(metaDir, "backlog.md"))
	if err != nil {
		b.WriteString("_Backlog not found._\n")
	} else {
		text := string(data)
		lines := strings.SplitN(text, "\n", 5)
		if len(lines) > 4 {
			b.WriteString(strings.Join(lines[4:], "\n"))
		} else {
			b.WriteString(text)
		}
	}
	return wikiPage{File: "Backlog.md", Title: "Backlog", Content: b.String()}
}

func buildChangelogPage(metaDir string) wikiPage {
	var b strings.Builder
	data, err := os.ReadFile(filepath.Join(metaDir, "CHANGELOG.md"))
	if err != nil {
		b.WriteString("_Changelog not found._\n")
	} else {
		versionHeadings := 0
		for _, line := range strings.Split(string(data), "\n") {
			if strings.HasPrefix(line, "## [") {
				versionHeadings++
			}
			if versionHeadings <= 10 {
				b.WriteString(line + "\n")
			} else {
				b.WriteString("\n_... older versions omitted._\n")
				break
			}
		}
	}
	return wikiPage{File: "Changelog.md", Title: "Changelog", Content: b.String()}
}

func buildKnownIssuesPage(metaDir string) wikiPage {
	var b strings.Builder
	data, err := os.ReadFile(filepath.Join(metaDir, "known-issues.md"))
	if err != nil {
		b.WriteString("_Known issues not found._\n")
	} else {
		writeFullDoc(&b, string(data))
	}
	return wikiPage{File: "Known-Issues.md", Title: "Known Issues", Content: b.String()}
}

func buildSecurityPage(root, docsDir string) wikiPage {
	var b strings.Builder
	readSection(root, "README.md", &b, 54, 61)
	b.WriteString("\n")
	data, err := os.ReadFile(filepath.Join(docsDir, "security.md"))
	if err != nil {
		b.WriteString("_Security document not found._\n")
	} else {
		writeFullDoc(&b, string(data))
	}
	return wikiPage{File: "Security.md", Title: "Security", Content: b.String()}
}

func buildBuildUsagePage(root string) wikiPage {
	var b strings.Builder
	readSection(root, "README.md", &b, 66, 77)
	return wikiPage{File: "Build-Usage.md", Title: "Build & Usage", Content: b.String()}
}

func buildConfigPage(refDir string) wikiPage {
	var b strings.Builder
	data, err := os.ReadFile(filepath.Join(refDir, "configuration.md"))
	if err != nil {
		b.WriteString("_Configuration document not found._\n")
	} else {
		writeFullDoc(&b, string(data))
	}
	return wikiPage{File: "Configuration.md", Title: "Configuration", Content: b.String()}
}

func buildReferenceDocsPage(refDir string) wikiPage {
	var b strings.Builder
	entries, _ := os.ReadDir(refDir)
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".md") {
			name := strings.TrimSuffix(e.Name(), ".md")
			title := strings.ReplaceAll(name, "-", " ")
			title = strings.ReplaceAll(title, "_", " ")
			title = strings.Title(title)
			b.WriteString(fmt.Sprintf("## [%s](https://github.com/coff33ninja/go-mcp-computer-use/blob/v0.2.x/docs/reference/%s)\n\n", title, e.Name()))
			if data, err := os.ReadFile(filepath.Join(refDir, e.Name())); err == nil {
				text := string(data)
				for _, line := range strings.Split(text, "\n") {
					if strings.HasPrefix(line, "> ") {
						b.WriteString(strings.TrimPrefix(line, "> "))
						break
					}
				}
			}
			b.WriteString("\n\n")
		}
	}
	return wikiPage{File: "Reference-Docs.md", Title: "Reference Docs", Content: b.String()}
}

func buildGuidesPage(guidesDir string) wikiPage {
	var b strings.Builder
	entries, _ := os.ReadDir(guidesDir)
	if len(entries) == 0 {
		b.WriteString("_No guides yet._\n")
	}
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".md") {
			name := strings.TrimSuffix(e.Name(), ".md")
			title := strings.ReplaceAll(name, "-", " ")
			title = strings.ReplaceAll(title, "_", " ")
			title = strings.Title(title)
			b.WriteString(fmt.Sprintf("- [%s](https://github.com/coff33ninja/go-mcp-computer-use/blob/v0.2.x/docs/guides/%s)\n", title, e.Name()))
		}
	}
	return wikiPage{File: "Guides.md", Title: "Guides", Content: b.String()}
}

func buildCICDPage(docsDir string) wikiPage {
	var b strings.Builder
	data, err := os.ReadFile(filepath.Join(docsDir, "ci-cd-pipeline.md"))
	if err != nil {
		b.WriteString("_CI/CD document not found._\n")
	} else {
		writeFullDoc(&b, string(data))
	}
	return wikiPage{File: "CICD.md", Title: "CI/CD Pipeline", Content: b.String()}
}

func readSection(root, file string, b *strings.Builder, start, end int) {
	data, err := os.ReadFile(filepath.Join(root, file))
	if err != nil {
		return
	}
	lines := strings.Split(string(data), "\n")
	for i, line := range lines {
		if i < start {
			continue
		}
		if i >= end {
			break
		}
		b.WriteString(line + "\n")
	}
}

func writeFullDoc(b *strings.Builder, text string) {
	lines := strings.SplitN(text, "\n", 4)
	if len(lines) > 3 {
		b.WriteString(strings.Join(lines[3:], "\n"))
	} else {
		b.WriteString(text)
	}
}
